### ISSUE TITLE
Switch Camera

### ISSUE THREAD

**Issue by ahmetozalp** [jeremija/peer-calls#81] opened 2020-03-31 11:40 UTC
Is it possible and how do I change the camera for mobile devices during the live broadcast?

**Comment by jeremija** [comment] 2020-03-31 12:28
You can press the hang up button and pick your camera again. Unfortunately it is not possible to change the camera stream without interrupting the audio stream at the moment.

**Comment by ahmetozalp** [comment] 2020-03-31 12:38
Doesn't the FacingMode user and environment event solve the problem?

**Comment by jeremija** [comment] 2020-04-02 23:13
In my experience `facingMode: 'user'` is unreliable, at least in Firefox Android. A possible alternative would be to cycle between all or the first two cameras found. Closing as duplicate of #30.

**Closed by jeremija** 2020-04-02 23:13 UTC
