### ISSUE TITLE
Integrate chat

### ISSUE THREAD

**Issue by matikbird** [jeremija/peer-calls#33] opened 2017-04-16 01:35 UTC
Hi!

If this repo can deploy a video from computer to computer,
where's the file I need to edit to pass text to make the videocall peer-to-peer more cool?

**Comment by jeremija** [comment] 2017-05-31 11:47
6bbabc1 added experimental (and ugly) chat feature via a peer connection. My plain is to add a full-fledged chat UI at some point, and to be able to switch between socket & peer connection for chat, just didn't have the time to do so.

**Comment by jeremija** [comment] 2017-06-18 13:30
Closing as duplicate of #12

**Closed by jeremija** 2017-06-18 13:30 UTC

**Comment by matikbird** [comment] 2017-07-01 15:58
Just tell me where to start.
I'll go with mostly plain JavaScript, no CSS-preprocessors nor JS-preprocessors I'd use.

I get the idea by that code, and implement a socket-chat beside it won't hurt and since socket.io launched 2.0, it's very fast indeed and not hard at all.
