### ISSUE TITLE
Custom bandwidth

### ISSUE THREAD

**Issue by litashg** [jeremija/peer-calls#82] opened 2020-04-03 17:26 UTC
Hello! I'm trying to build a multi-room video chat based on your code. I have a problem with video when more than 4-5 users come into the room at one time. I want to try set bandwidth on 250 kbps. Like in that demo. https://webrtc.github.io/samples/src/content/peerconnection/bandwidth/

Can you help me to find a way to do it? Maybe some config, etc...

**Comment by jeremija** [comment] 2020-04-03 20:17
Hi @litashg, Thanks for your interest in Peer Calls!

This is a tricky problem because all peers in Peer Calls establish a mesh network, which means one user ends up uploading their own video to every other connected user in the room. Based on the example you listed, looks like you'd need to take out the [`updateBandwidthRestriction`][1] function, and then call it from the [`sdpTransform`][2] function of `simple-peer`. This function needs to be set in the [new Peer][3] constructor. Note that the signature of `sdpTransform` function is `(sdp: string) => (string)`, so you'll need to adapt the original function, for example:

```typescript
const createSdpTransform = (bandwidth: number) =>
  (sdp: string) => updateBandwidthRestriction(sdp, bandwidth)
```

A better solution to this problem would be to use a [SFU][4] (selective forwarding unit), to which all users would upload their video, and the SFU would distribute it to others as needed. I'm currently working on Peer Calls v4, which is a full rewrite of the server in Go, and it will (hopefully) ship with a built-in SFU.

[1]: https://github.com/webrtc/samples/blob/4318a1f37b78b056892bdd995ace66e65ba67a3f/src/content/peerconnection/bandwidth/js/main.js#L225-L238

[2]: https://github.com/feross/simple-peer/issues/471

[3]: https://github.com/jeremija/peer-calls/blob/6b865a78bbb4e64e981212b0a0e741741f8f9196/src/client/actions/PeerActions.ts#L175

[4]: https://webrtcglossary.com/sfu/

**Comment by litashg** [comment] 2020-04-04 07:06
Hi @jeremija . Thank you for your fast response. 
I will try to rewrite the original function, maybe it can help me. 

How do you think, do I have any chances to have a nice performance when 10 ppl come into the room if I use mesh network?

Maybe you can advise me on some SFU decisions based on node js? I found only [mediasoup](https://github.com/mganeko/mediasoup_v3_example) but their npm installer is bugged. 

In sympathy to you and your work, Hennadii.

**Comment by jeremija** [comment] 2020-04-04 07:29
Perhaps if you limit the bandwidth you'll have better success. I'd be curious to hear your findings once you try it out.

I've heard about mediasoup, but I've never used it. Then there is [kurento media server][1]. Some people using simple-peer mentioned it as a good option. It can serve as an SFU, it has a websocket API, a NodeJS client library on npm, thorough documentation and lots of sample apps in Java and NodeJS, but it's written in C++. The reason why I didn't end up using it is because the client library was still using callbacks.

Then I ran into [pion/webrtc][2], so now I'm using this library to implement my own solution, but it will be written in Golang.

[1]: https://www.kurento.org/
[2]: https://github.com/pion/webrtc

**Comment by litashg** [comment] 2020-04-04 12:55
One more question. I saw that when I use Firefox - one client can handle 4-5 streams without rendering errors. I think it because Firefox uses h264 by default. Maybe if I set H264 as default codec - the application can work more stable. Any idea of how to do that experiment?

**Comment by jeremija** [comment] 2020-04-04 13:17
Are you referring to video render errors, or a bug in application code? You can filter the SDP and only leave the a=rtpmap entries for H264. You'd also need to make sure you remove the filtered out the payload types of removed codecs from related `m=video` section(s).

**Comment by litashg** [comment] 2020-04-04 15:33
I think it`s all about a bug in application code (react rendering errors). I want to ask my friend who familiar with react to help me fix it. Maybe we can check if a stream is rendering correct, else - just reload 'video' tag. 
Thanks for the solution. I will try it.

**Comment by jeremija** [comment] 2020-04-04 15:35
Oh, but this is in your dev code? Or does the same bug happen on peercalls.com as well?

**Comment by litashg** [comment] 2020-04-04 15:40
I found this bug on peercalls.com . If more than 3 users in a room more than 15-20 seconds one-two 'video' tags can fall and show only last frame. Maybe it's all because of my mac's CPU is overloaded.

**Comment by jeremija** [comment] 2020-04-04 15:44
Got it, thanks for sharing. I'll look into it as well.

**Comment by litashg** [comment] 2020-04-04 15:52
I can help you to found that bug if you need a help.

**Comment by ahmetozalp** [comment] 2020-04-04 15:52
Yes, if the user has logged out, the saddle screen remains the last video.

**Comment by jeremija** [comment] 2020-04-04 15:57
Do you see a message in the top console saying something like "cannot remove a track that was not added"?

**Comment by litashg** [comment] 2020-04-04 16:00
![Screen Shot 2020-04-04 at 6 58 51 PM](https://user-images.githubusercontent.com/31222500/78455357-82d70600-76a6-11ea-8711-645f3bb038da.png)

I make a screenshot.

**Comment by litashg** [comment] 2020-04-04 16:02
4 connects at time. Only 1 'video' tag is active, 2-3-4 falls.

**Comment by jeremija** [comment] 2020-04-04 16:05
So they stop working after the fourth user connects? Because I just tested this with four devices and I could see all videos, albeit some were a little slow.

**Comment by litashg** [comment] 2020-04-04 16:07
Yes. It strange, and I think it's all because my mac can't handle 4 connections at time.

**Comment by litashg** [comment] 2020-04-04 16:12
And I can't find why it shows message - 'Connected users : 5'. Why socket event 'users' activates 2 times without new connections.

**Comment by jeremija** [comment] 2020-04-04 16:14
Are you connected to network via WiFi? If so, your access point could also be the bottleneck. For devices will be sending a total of 4*3 videos to each other. If we say one video is 500Kbit/s - 1Mbit/s, that could be 6 - 12Mbit/s for four users.

**Comment by jeremija** [comment] 2020-04-04 16:15
The `users` event will fire on reconnect, but no new connections should be made if peer connections are already active. Weird that it says `5` users if only `4` are connected.

**Comment by jeremija** [comment] 2020-04-04 16:20
It could be that the `disconnect` event hasn't happened yet on the server-side and the old socket connection was still included in the `users` list.

**Comment by litashg** [comment] 2020-04-04 16:22
My connection is wifi ~35 Mbps for download and upload.

**Comment by litashg** [comment] 2020-04-04 16:24
It's some delay between user close browser and server shot `disconnect`. I'll look at how to avoid that.

**Comment by jeremija** [comment] 2020-04-04 16:27
My working branch for v4 (`server-go`) uses sets or hashmaps with IDs coming from the client-side so this shouldn't happen there. In v3 I'm relying on socket.io for this data, and that library seems to generate a new ID for every new connection.

**Comment by jeremija** [comment] 2020-04-04 16:28
This is what I was asking about:

![image](https://user-images.githubusercontent.com/1489493/78456106-16f29e80-76a2-11ea-88d9-9ca1d6aeeee1.png)

This happens on peer connection error.

**Comment by ahmetozalp** [comment] 2020-04-04 16:31
Hiding the screen in video.tsx when Camera or Sound is turned off?

**Comment by jeremija** [comment] 2020-04-04 16:40
@ahmetozalp can you clarify? I'm not sure I understand :)

**Comment by ahmetozalp** [comment] 2020-04-04 17:04
![GitHub Logo](https://i.imgur.com/sNrmBpL.png)

**Comment by ahmetozalp** [comment] 2020-04-04 17:05
2th screen bug.

**Comment by ahmetozalp** [comment] 2020-04-04 17:19
stun links: google

**Comment by ahmetozalp** [comment] 2020-04-04 17:31
I found the problem, the problem is slow, the connection is lost on the internet

**Comment by litashg** [comment] 2020-04-04 17:32
Result of reducing bandwidth to 125kbps - 5 different users in one Chrome client window without lags and disconnects on my early 11 macbook pro. Nice result. 

But if one of the video clients falls - I need to reload the page. And your fix of removing video tag on user disconnect works perfectly.

**Comment by ahmetozalp** [comment] 2020-04-04 19:14
can you share it if it succeeds?

**Comment by litashg** [comment] 2020-04-05 07:29
Added to PeerAction.ts 

```

const createSdpTransform = (bandwidth: number) =>
  (sdp: string) => updateBandwidthRestriction(sdp, bandwidth)

```
```

function updateBandwidthRestriction(sdp: any, bandwidth:any) {
  let modifier = 'AS';
  if (sdp.indexOf('b=' + modifier + ':') === -1) {
    // insert b= after c= line.
    sdp = sdp.replace(/c=IN (.*)\r\n/, 'c=IN $1\r\nb=' + modifier + ':' + bandwidth + '\r\n');
  } else {
    sdp = sdp.replace(new RegExp('b=' + modifier + ':.*\r\n'), 'b=' + modifier + ':' + bandwidth + '\r\n');
  }
  return sdp;
}

```

And added param to 

`const peer = new Peer({
      initiator: userId === initiator,
      config: { iceServers },
      sdpTransform: createSdpTransform(125),
      // Allow the peer to receive video, even if it's not sending stream:
      // https://github.com/feross/simple-peer/issues/95
      offerConstraints: {
        offerToReceiveAudio: true,
        offerToReceiveVideo: true,
      },
      stream,
    })`

**Comment by litashg** [comment] 2020-04-05 07:30
I don't know react, so I just hardcoded param.

**Comment by litashg** [comment] 2020-04-05 08:58
Gospodine Jerko, I need your advice. I found one more WebRTC realization - https://whereby.com/sobakabarabaka (demo room), please, tell me if you know, how do they reload video tag ? If I load 4 users from a low-performance client - video renders slowly, sometimes freeze but it never off.  Can you show me a direction of what to read or what to google?

**Comment by jeremija** [comment] 2020-04-05 09:47
Are you using Chrome by chance? Can you try commenting out the `track.onmute` handler [here](https://github.com/jeremija/peer-calls/blob/4a089b52f3a84fad39b19f3ec54288b5d48c1bd1/src/client/actions/PeerActions.ts#L86-L90) and see if that fixes the issue?

**Comment by litashg** [comment] 2020-04-05 10:20
Brilliance! Chat handled 8 connections at a time. Even from the phone, from old mac, from windows tablet or android tablet. I think It can handle more connections but we don't have more devices)) You are the smartest person ever. Thank you!

**Comment by litashg** [comment] 2020-04-05 10:21
And no matter what browser I use. Chrome, Opera, Firefox and noname Xiaomi browser.

**Comment by jeremija** [comment] 2020-04-05 10:23
Haha, thanks for your kind words, and thanks for pointing out this bug. I'm going to add a fix for this shortly.

**Comment by litashg** [comment] 2020-04-05 10:26
If you need - I can help you to handle as more bugs as I can find.

**Comment by jeremija** [comment] 2020-04-05 10:27
That would be great, thanks so much!

**Comment by jeremija** [comment] 2020-04-05 10:54
@litashg Would you mind testing my fix in 949a09f4 (latest commit on master)?

**Comment by litashg** [comment] 2020-04-05 11:02
Yes. Wait a few minutes. 

And one more bug - if you click "Join Call" more than one time - it will create few video tags. 
![Screen Shot 2020-04-05 at 2 02 22 PM](https://user-images.githubusercontent.com/31222500/78473021-1d3a5680-7746-11ea-8b83-b6ec4d2dcfc1.png)

**Comment by jeremija** [comment] 2020-04-05 11:09
Ah, thanks for reporting this!

**Comment by litashg** [comment] 2020-04-05 11:21
I tried your fix. Works great. But when a stream is removed - the last frame in video tag zoomed. Than stream reloads and play nice until next remove and frame zoom. I found this only in Chrome. It's really strange when video screen content suddenly jumps in zoom.

**Comment by litashg** [comment] 2020-04-05 11:21
I can make video if you need it.

**Comment by jeremija** [comment] 2020-04-05 11:22
Thanks, a video would be helpful!

**Comment by litashg** [comment] 2020-04-05 11:33
https://drive.google.com/open?id=1n5HL6evYLYg1I1gKvPjZ9B0xHP_Zy0q3

**Comment by ahmetozalp** [comment] 2020-04-05 11:53
@litashg can you give me access

**Comment by litashg** [comment] 2020-04-05 12:34
@jeremija @ahmetozalp access granted.

**Comment by jeremija** [comment] 2020-04-05 12:50
Thanks for sharing! @ahmetozalp, is this the same issue you wrote about above?

@litashg, can you share the steps to reproduce this behavior? Is this on 949a09f ? Is it a poor network connection, or something else?

**Comment by litashg** [comment] 2020-04-05 12:59
I just opened 3 browser windows in one channel. My CPU was overloaded and some video streams fall and reload. Yes, it's happening on [949a09f](https://github.com/jeremija/peer-calls/commit/949a09f4b10892942ed8eee2a6193d33e30263cd). And the previous fix with removing dispatch works much better. Do you really need to remove track when the CPU cannot render the video stream fast? 

```
dispatch(StreamActions.removeTrack({
        userId,
        stream,
        track,
      }))
```

**Comment by jeremija** [comment] 2020-04-05 13:11
Thanks! The `onmute` is the only event we can listen to see that the remote peer has stopped sharing their video. This is an issue because the users can be sharing two video tracks: webcam video and desktop capture.

Since most browsers have switched to [Unified Plan](https://docs.google.com/document/d/1-ZfikoUtoJa9k-GZG1daN0BU3IjIanQ_JSscHxQesvU/edit), there is no guarantee that the `MediaStreamTrack.onended` event will ever fire:

> #### MediaStreamTrack.onended No Longer Fires
> Because remote tracks may be muted but are never removed, MediaStreamTrack.onended no longer fires. Instead, rely on MediaStreamTrack.onmute to discover if a track is removed. See [code snippet](https://codepen.io/anon/pen/EdbWgY?editors=0010)​.

Let me try to reproduce this and see if there's anything I can think of...

**Comment by jeremija** [comment] 2020-04-05 13:28
Is this it? I am not able to reproduce the stretched picture, though.

![peercalls](https://user-images.githubusercontent.com/1489493/78499598-dd796c00-7751-11ea-8a24-9cf84d67d725.gif)

**Comment by litashg** [comment] 2020-04-05 13:35
Also, is it ok if I share screen and people see 2 video streams? One from my camera and second from my screen?

**Comment by litashg** [comment] 2020-04-05 13:37
Look like it depends on CPU, I don't see anything strange on your demo.

**Comment by jeremija** [comment] 2020-04-05 13:38
The video tracks are being muted (removed) and unmuted (added again) in a loop.

**Comment by jeremija** [comment] 2020-04-05 13:39
> Also, is it ok if I share screen and people see 2 video streams? One from my camera and second from my screen?

I would assume so. Other software behaves similarly - you can see both the screen and the speaker.

**Comment by ahmetozalp** [comment] 2020-04-05 13:48
While the problem is slow video recording from the internet, do a speedtest from a computer with 10megabit or 20megabit internet and you will see the problem in the upload.

My suggestion is to get it reconnected, but how can it be done?

**Comment by litashg** [comment] 2020-04-05 13:48
And what if you don't mute the track? It looks like it rendering speed becomes slower.

**Comment by litashg** [comment] 2020-04-05 13:52
@ahmetozalp in my opinion - the bottleneck is rendering speed.

**Comment by jeremija** [comment] 2020-04-05 13:56
> While the problem is slow video recording from the internet, do a speedtest from a computer with 10megabit or 20megabit internet and you will see the problem in the upload.

Yes, the main problem with mesh network in this situation is the asymmetric download/upload speeds. The common upload speeds on common internet connections are usually an order of magnitude lower than the download speed.

As @litashg mentioned, the CPU power is also a factor. But when testing locally on the same device, the performance will always be worse than when testing on, say, two devices. In the first case a single device would be doing all the encoding, sending, and decoding, where in the second case the two devices will each do half of the work.

> My suggestion is to get it reconnected, but how can it be done?

I do not think a reconnect is needed with the fixes from 949a09f, because the stream will still get to send some data over time, and the track will be unmuted eventually. I'm going to try to make some UI changes and not hide the video container as soon as the video track is muted (and the peer still exists)...

**Comment by jeremija** [comment] 2020-04-05 14:10
Please test e9e0ab8 (branch `track-muted-fix`) and let me know if this looks a little better now?

**Comment by ahmetozalp** [comment] 2020-04-05 15:29
there is nothing altogether changing

**Comment by jeremija** [comment] 2020-04-05 15:30
What do you mean nothing's changing? The video boxes should no longer be disappearing. What are you testing?

**Comment by litashg** [comment] 2020-04-05 15:51
Look better. I don't even see any zooms.

**Comment by litashg** [comment] 2020-04-05 17:20
![Screen Shot 2020-04-05 at 8 15 53 PM](https://user-images.githubusercontent.com/31222500/78505243-d450c500-777a-11ea-9108-1ec8a234c151.png)
One of the best results. 12 ppl in one group.

**Comment by jeremija** [comment] 2020-04-05 17:29
Thanks for sharing!! Is this with bandwidth limiting or no?

**Comment by litashg** [comment] 2020-04-05 17:35
Limit is 125 kbps. Sometimes video track renders slowly, but nothing falls. Great result I say. Thanks to you.

**Comment by jeremija** [comment] 2020-04-05 18:10
Thanks for sharing!!! Glad I was able to help and please report any issues you run across.

**Closed by jeremija** 2020-04-05 18:10 UTC
Labels: question

**Comment by litashg** [comment] 2020-04-05 19:22
Thank you! If I found any bug or code some new feature - I will write to you.

**Comment by ahmetozalp** [comment] 2020-04-05 19:34
@litashg  Hello, do you try to do internet speed test on a different tab during speaking, I still have the same problem

**Comment by litashg** [comment] 2020-04-05 20:03
@ahmetozalp Any problems with internet speed. Max for 12 client was 10mbps for receiving and ~1.5 for sending. You should try to test on different devices. Not in one browser.

**Comment by Llorx** [comment] 2021-10-20 18:07
> Hi @litashg, Thanks for your interest in Peer Calls!
> 
> This is a tricky problem because all peers in a Peer Calls room establish a mesh network, which means every user ends up uploading their own video to every other connected user. Based on the example you listed, looks like you'd need to take out the [`updateBandwidthRestriction`](https://github.com/webrtc/samples/blob/4318a1f37b78b056892bdd995ace66e65ba67a3f/src/content/peerconnection/bandwidth/js/main.js#L225-L238) function, and then call it from the [`sdpTransform`](https://github.com/feross/simple-peer/issues/471) function of `simple-peer`. This function needs to be set in the [new Peer](https://github.com/jeremija/peer-calls/blob/6b865a78bbb4e64e981212b0a0e741741f8f9196/src/client/actions/PeerActions.ts#L175) constructor. Note that the signature of `sdpTransform` function is `(sdp: string) => (string)`, so you'll need to adapt the original function, for example:
> 
> ```ts
> const createSdpTransform = (bandwidth: number) =>
>   (sdp: string) => updateBandwidthRestriction(sdp, bandwidth)
> 
> const peer = new Peer({
>   sdpTransform: createSdpTransform(250),
>   ...
> })
> ```
> 
> A better solution to this problem would be to use a [SFU](https://webrtcglossary.com/sfu/) (selective forwarding unit), to which all users would upload their own videos, and the SFU would distribute it to others as needed. I'm currently working on Peer Calls v4, which is a full rewrite of the server in Go, and it will (hopefully) ship with a built-in SFU.

This works like a charm. Thank you.
